In [1]:
import numpy as np

# Sort( )

In [ ]:
# np.sort-Return a sorted copy of an array.


In [11]:
np.random.seed(49)
a = np.random.randint(1,100,15)
a

array([43, 46, 41, 55, 13, 70,  6, 50, 19, 37, 13, 97, 83, 27,  7])

In [13]:
np.sort(a)    # for descending-np.sort(a)[::-1]

array([ 3,  9, 13, 20, 30, 35, 38, 53, 54, 54, 57, 64, 67, 79, 97])

In [3]:
b =  np.random.randint(1,100,24).reshape(6,4)
b

array([[42,  2,  1, 71],
       [49, 49, 72, 21],
       [89, 84, 25, 64],
       [10,  3, 55, 19],
       [69, 43,  5, 30],
       [93, 88, 73, 15]])

In [10]:
np.sort(b,axis=0)

array([[12, 38, 10,  4],
       [28, 47, 60, 22],
       [31, 48, 73, 30],
       [41, 49, 92, 66],
       [62, 96, 95, 78],
       [82, 99, 98, 90]])

# Append ( )

In [14]:
np.append(a,200)

array([ 57,  64,  30,  20,  79,  38,  53,  35,  67,   9,  54,  13,   3,
        97,  54, 200])

In [17]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[96., 90., 88., 20.,  1.],
       [18., 68., 13., 57.,  1.],
       [81., 26., 31., 82.,  1.],
       [89., 85., 29., 17.,  1.],
       [ 8., 37., 18., 65.,  1.],
       [64., 36., 44., 22.,  1.]])

# Concatenate ( )

In [2]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [3]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# Unique ( )

In [5]:
e = np.array([1,1,1,1,2,3,4,4,4,5,6,7,7,8])
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8])

# Expand_dims ( )

In [7]:
# We can get the expanded dimension of array
a

array([31, 52, 49, 62, 34, 89, 11, 20, 41, 62, 56, 44, 40, 76, 48])

In [13]:
print(np.expand_dims(a,axis=0))
print(np.expand_dims(a,axis=0).shape)

[[31 52 49 62 34 89 11 20 41 62 56 44 40 76 48]]
(1, 15)


In [14]:
print(np.expand_dims(a,axis=1).shape)
np.expand_dims(a,axis=1)

(15, 1)


array([[31],
       [52],
       [49],
       [62],
       [34],
       [89],
       [11],
       [20],
       [41],
       [62],
       [56],
       [44],
       [40],
       [76],
       [48]])

# Where ( )

In [15]:
a

array([31, 52, 49, 62, 34, 89, 11, 20, 41, 62, 56, 44, 40, 76, 48])

In [24]:
np.where(a>50)

(array([ 1,  3,  5,  9, 10, 13], dtype=int64),)

In [25]:
a[(np.where(a>50))]

array([52, 62, 89, 62, 56, 76])

In [23]:
np.where(a>50,0,a)  # [Condition,True,False]

array([31,  0, 49,  0, 34,  0, 11, 20, 41,  0,  0, 44, 40,  0, 48])

# argmax ( )

In [12]:
# argmax() retturns indices of max element of the array in a perticular axis
a

array([43, 46, 41, 55, 13, 70,  6, 50, 19, 37, 13, 97, 83, 27,  7])

In [13]:
np.argmax(a)

11

In [14]:
b

array([[42,  2,  1, 71],
       [49, 49, 72, 21],
       [89, 84, 25, 64],
       [10,  3, 55, 19],
       [69, 43,  5, 30],
       [93, 88, 73, 15]])

In [15]:
np.argmax(b,axis=0)  #col

array([5, 5, 5, 0], dtype=int64)

In [16]:
np.argmax(b,axis=1)  #row

array([3, 2, 0, 2, 0, 0], dtype=int64)

In [17]:
# argmin() - retturns indices of min element of the array in a perticular axis
np.argmin(a)

6

# cumsum ( )

In [19]:
# cumsum() function is used when we want to compute the cumulative sum of array of elements over a given axis

In [20]:
np.cumsum(a)

array([ 43,  89, 130, 185, 198, 268, 274, 324, 343, 380, 393, 490, 573,
       600, 607])

In [21]:
np.cumsum(b,axis=0)

array([[ 42,   2,   1,  71],
       [ 91,  51,  73,  92],
       [180, 135,  98, 156],
       [190, 138, 153, 175],
       [259, 181, 158, 205],
       [352, 269, 231, 220]])

In [23]:
# cumprod()- function is used when we want to compute the cumulative product of array of elements over a given axis
np.cumprod(a)

array([         43,        1978,       81098,     4460390,    57985070,
        -236012396, -1416074376, -2084242064,  -945893552,  -638323056,
         291734864, -1766489264,  -589720848,  1257406288,   211909424])

# percentile ( )

In [25]:
# percentile () - it is used to compute nth percentile of the given data (array elements) along the specific axis

In [26]:
a

array([43, 46, 41, 55, 13, 70,  6, 50, 19, 37, 13, 97, 83, 27,  7])

In [27]:
np.percentile(a,100)

97.0

# histogram ( )

In [32]:
# histogram () represents the frequency of data distribution
# bins - range

In [31]:
np.histogram(a,bins=[0,50,100])

(array([10,  5], dtype=int64), array([  0,  50, 100]))

# corrcoef ( )

In [33]:
# corrcoef () - return pearson product-moment correlation coefficient

In [34]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# isin ( )

In [37]:
#The numpy.isin() method provides a way to check whether elements of oneNumPy array exist in another array 
# and returns a boolean array indicating which elements are present

In [35]:
a

array([43, 46, 41, 55, 13, 70,  6, 50, 19, 37, 13, 97, 83, 27,  7])

In [38]:
np.isin(a,np.arange(1,50))

array([ True,  True,  True, False,  True, False,  True, False,  True,
        True,  True, False, False,  True,  True])

In [39]:
a[np.isin(a,np.arange(1,50))]

array([43, 46, 41, 13,  6, 19, 37, 13, 27,  7])

# flip ( )

In [ ]:
# The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [48]:
np.flip(a)
#a[::-1]

array([  7,  27,  83,  97,  13,  37,  19,  50,   6,  70,  13,  55,  41,
       120, 110])

In [41]:
np.flip(b)

array([[15, 73, 88, 93],
       [30,  5, 43, 69],
       [19, 55,  3, 10],
       [64, 25, 84, 89],
       [21, 72, 49, 49],
       [71,  1,  2, 42]])

# put ( )

In [ ]:
# The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

In [42]:
a

array([43, 46, 41, 55, 13, 70,  6, 50, 19, 37, 13, 97, 83, 27,  7])

In [45]:
np.put(a,[0,1],[110,120])  # [arr.name, index, value]
a

array([110, 120,  41,  55,  13,  70,   6,  50,  19,  37,  13,  97,  83,
        27,   7])

# del ( )

In [ ]:
# The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [54]:
np.delete(a,[0,1])

array([41, 55, 13, 70,  6, 50, 19, 37, 13, 97, 83, 27,  7])

# Set functions

In [58]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [59]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [60]:
np.intersect1d(m,n)

array([3, 4, 5])

In [62]:
print(np.setdiff1d(m,n))
print(np.setdiff1d(n,m))

[1 2]
[6 7]


In [63]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [66]:
# numpy.in1d() function test whether each element of a 1-D array is also present in a second array and 
# return a boolean array the same length as arr1 that is True where an element of arr1 is in arr2 and False otherwise.

In [67]:
np.in1d(m,1)

array([ True, False, False, False, False])

In [65]:
m[np.in1d(m,1)]

array([1])

# Clip ( )

In [ ]:
# numpy.clip() function is used to Clip (limit) the values in an array. Given an interval, 
# values outside the interval are clipped to the interval edges. For example, if an interval of [0, 1] is specified,
# values smaller than 0 become 0, and values larger than 1 become 1.

In [68]:
a

array([110, 120,  41,  55,  13,  70,   6,  50,  19,  37,  13,  97,  83,
        27,   7])

In [69]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 41, 55, 25, 70, 25, 50, 25, 37, 25, 75, 75, 27, 25])